# Generated by Django 2.2 on 2019-04-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
