# Generated by Django 2.2 on 2019-04-29 09:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0002_auto_20190428_2336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneModel',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
