# Generated by Django 2.2 on 2019-04-29 20:13

from django.db import migrations, models
import django.db.models.deletion
import testsys.models


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0003_auto_20190429_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.CharField(max_length=50)),
                ('RemoteAccountID', models.CharField(max_length=50)),
                ('RemoteWebServiceHost', models.CharField(max_length=100)),
                ('remoteserviceid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentid', models.CharField(max_length=10)),
                ('foreigndeviceguid', models.CharField(max_length=50)),
                ('policyid', models.CharField(max_length=10)),
                ('agentversion', models.CharField(max_length=20)),
                ('agentstate', models.CharField(choices=[(testsys.models.AgentStateType('0'), '0'), (testsys.models.AgentStateType('1'), '1'), (testsys.models.AgentStateType('2'), '2'), (testsys.models.AgentStateType('3'), '3'), (testsys.models.AgentStateType('4'), '4'), (testsys.models.AgentStateType('5'), '5'), (testsys.models.AgentStateType('6'), '6'), (testsys.models.AgentStateType('7'), '7'), (testsys.models.AgentStateType('8'), '8'), (testsys.models.AgentStateType('9'), '9'), (testsys.models.AgentStateType('10'), '10'), (testsys.models.AgentStateType('13'), '13'), (testsys.models.AgentStateType('14'), '14'), (testsys.models.AgentStateType('15'), '15'), (testsys.models.AgentStateType('16'), '16'), (testsys.models.AgentStateType('17'), '17')], max_length=1)),
                ('agentstatename', models.CharField(choices=[(testsys.models.AgentStateType('0'), '0'), (testsys.models.AgentStateType('1'), '1'), (testsys.models.AgentStateType('2'), '2'), (testsys.models.AgentStateType('3'), '3'), (testsys.models.AgentStateType('4'), '4'), (testsys.models.AgentStateType('5'), '5'), (testsys.models.AgentStateType('6'), '6'), (testsys.models.AgentStateType('7'), '7'), (testsys.models.AgentStateType('8'), '8'), (testsys.models.AgentStateType('9'), '9'), (testsys.models.AgentStateType('10'), '10'), (testsys.models.AgentStateType('13'), '13'), (testsys.models.AgentStateType('14'), '14'), (testsys.models.AgentStateType('15'), '15'), (testsys.models.AgentStateType('16'), '16'), (testsys.models.AgentStateType('17'), '17')], max_length=50)),
                ('currentdefinitionsversion', models.CharField(max_length=10)),
                ('currentdefinitionsdate', models.DateField()),
                ('sdkproductversion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AlertsBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateField()),
                ('alert_id', models.CharField(max_length=50)),
                ('alerttimestamp', models.DateField()),
                ('alertstate', models.CharField(choices=[(testsys.models.AlertState('0'), '0'), (testsys.models.AlertState('1'), '1'), (testsys.models.AlertState('2'), '2')], max_length=1)),
                ('external_service_id', models.CharField(choices=[(testsys.models.ExternalService('1'), '1'), (testsys.models.ExternalService('2'), '2'), (testsys.models.ExternalService('3'), '3')], max_length=1)),
                ('rm_region', models.CharField(max_length=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsys.Account')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsys.Agent')),
            ],
        ),
    ]
