# Generated by Django 2.2 on 2019-04-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0004_account_agent_alertsbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='currentdefinitionsversion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
