# Generated by Django 2.2 on 2019-05-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0006_auto_20190430_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agentstate',
        ),
        migrations.AlterField(
            model_name='agent',
            name='agentstatename',
            field=models.CharField(choices=[('0', 'UNKNOWN'), ('1', 'IDLE'), ('2', 'SCANNING'), ('3', 'SNOOZED'), ('4', 'DEACTIVATED'), ('5', 'DOWNLOADING_ENGINE'), ('6', 'INSTALLING_ENGINE'), ('7', 'ENGINE_INSTALL_FAILED'), ('8', 'UNINSTALLED'), ('9', 'INSTALLING'), ('10', 'INSTALL_COMPLETE'), ('13', 'COMPETETIVE_REMOVAL'), ('14', 'COMPETETIVE_REMOVAL_FAILED'), ('15', 'COMPETETIVE_PRODUCT_DETECTED'), ('16', 'DOWNLOADING_COMPETETIVE_REMOVER'), ('17', 'INSTALLING_COMPETETIVE_REMOVER')], max_length=1),
        ),
    ]
