# Generated by Django 2.2 on 2019-05-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0007_auto_20190501_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsbody',
            name='alertstate',
            field=models.CharField(choices=[('0', 'UNDEFINED'), ('1', 'NEW'), ('2', 'RESOLVED')], max_length=1),
        ),
        migrations.AlterField(
            model_name='alertsbody',
            name='external_service_id',
            field=models.CharField(choices=[('1', 'AVERY'), ('2', 'BRECK'), ('3', 'ECHO')], max_length=1),
        ),
    ]
