# Generated by Django 2.2 on 2019-05-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0008_auto_20190501_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='foreigndeviceguid',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='alertsbody',
            name='alert_id',
            field=models.CharField(max_length=80),
        ),
    ]
