# Generated by Django 2.2 on 2019-05-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0011_auto_20190502_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
