# Generated by Django 2.2 on 2019-05-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0013_auto_20190502_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='RemoteAccountID',
            field=models.CharField(max_length=50, verbose_name='Remote Account ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='RemoteWebServiceHost',
            field=models.CharField(max_length=100, verbose_name='Remote WebService Host'),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountid',
            field=models.CharField(max_length=50, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='remoteserviceid',
            field=models.CharField(max_length=50, verbose_name='Remote Service ID'),
        ),
    ]
