# Generated by Django 2.2 on 2019-05-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0015_auto_20190502_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertsbody',
            options={'verbose_name': 'Body', 'verbose_name_plural': 'Bodies'},
        ),
    ]
