# Generated by Django 2.2 on 2019-05-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0016_auto_20190505_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertsbody',
            options={'verbose_name': 'Body', 'verbose_name_plural': 'Alerts Bodies'},
        ),
    ]
