# Generated by Django 2.2 on 2019-05-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0017_auto_20190505_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertsbody',
            options={'verbose_name': 'Alerts Body', 'verbose_name_plural': 'Alerts Bodies'},
        ),
    ]
