# Generated by Django 2.2 on 2019-05-25 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0060_auto_20190525_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsbody',
            name='alerttimestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 25, 15, 51, 38, 872718, tzinfo=utc), null=True, verbose_name='Alert Timestamp'),
        ),
    ]
