# Generated by Django 2.2 on 2019-05-25 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0061_auto_20190525_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsbody',
            name='alerttimestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 25, 16, 2, 10, 174558, tzinfo=utc), null=True, verbose_name='Alert Timestamp'),
        ),
    ]
