# Generated by Django 2.2 on 2019-05-25 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0064_auto_20190525_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsbody',
            name='alerttimestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 25, 16, 28, 51, 77110, tzinfo=utc), null=True, verbose_name='Alert Timestamp'),
        ),
    ]
