# Generated by Django 2.2 on 2019-05-25 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testsys', '0069_auto_20190525_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsbody',
            name='alerttimestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 25, 18, 45, 0, 191275, tzinfo=utc), null=True, verbose_name='Alert Timestamp'),
        ),
    ]
