# Generated by Django 2.2 on 2019-05-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20190511_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='owner',
        ),
    ]
