# Generated by Django 2.2 on 2019-05-17 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_auto_20190511_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('owner', 'state', 'created_date')},
        ),
        migrations.AddField(
            model_name='todo',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 17, 16, 40, 9, 574995, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='todo',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
