# Generated by Django 2.2 on 2019-05-17 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_auto_20190517_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 17, 16, 46, 18, 454824, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
