# Generated by Django 2.2 on 2019-05-17 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_auto_20190517_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 17, 19, 30, 56, 924492, tzinfo=utc)),
        ),
    ]
