# Generated by Django 2.2 on 2019-05-19 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_auto_20190517_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 9, 12, 51, 171001, tzinfo=utc)),
        ),
    ]
