# Generated by Django 2.2 on 2019-05-19 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0015_auto_20190519_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 10, 45, 49, 216532, tzinfo=utc)),
        ),
    ]
