# Generated by Django 2.2 on 2019-05-19 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0017_auto_20190519_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 11, 12, 41, 832602, tzinfo=utc)),
        ),
    ]
