# Generated by Django 2.2 on 2019-05-19 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0018_auto_20190519_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 19, 13, 47, 10, 867915, tzinfo=utc)),
        ),
    ]
