# Generated by Django 2.2 on 2019-05-23 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0022_auto_20190519_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 23, 9, 29, 38, 653029, tzinfo=utc)),
        ),
    ]
