# Generated by Django 2.2 on 2019-05-23 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0023_auto_20190523_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 23, 9, 38, 15, 285650, tzinfo=utc)),
        ),
    ]
