# Generated by Django 2.2 on 2019-05-25 08:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0045_auto_20190524_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 25, 8, 28, 5, 531003, tzinfo=utc)),
        ),
    ]
