# Generated by Django 2.2 on 2019-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0049_auto_20190525_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
